[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# Disable Next.js plugin for Vite project
[plugins]
  # No plugins needed for Vite

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
